name: on-commit
on: [push]
jobs:
  test-tap-apifootball:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: |
          poetry install
      - name: Run Tests for Tap APIFootball
        run: |
          poetry run pytest